# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: genshin-sign
        uses: daye99/genshin-sign-helper@master
        with: 
          node-version: "16"
        env: 
          COOKIE: ${{secrets.COOKIE}}
          SENDKEY: ${{secrets.SENDKEY}}
        run: |
          "npm i pnpm -g"
          "pnpm i"
          "node ./index.js"
